// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://nhxgdxedvpxqgrxwlkbq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5oeGdkeGVkdnB4cWdyeHdsa2JxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ2MDg2NDYsImV4cCI6MjA4MDE4NDY0Nn0.6sIwvm0aionQ3xD4PaGy6BGDUkANe_K2x0zHUaPXN1c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);